create database DB_QLCAFE

CREATE TABLE KHACHHANG
(
	MAKH INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	SDT CHAR(11) ,
	DIACHI NVARCHAR(50),
	GIOITINH NVARCHAR(50) ,
)

CREATE TABLE SANPHAM
(
	TENSP NVARCHAR(50) primary key NOT NULL,
	NGUYENLIEU NVARCHAR(50) NOT NULL,
	DONGIANHAP int NOT NULL,
	DONGIABAN int NOT NULL,
)
CREATE TABLE BOPHANLAMVIEC
(
	MABP INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENBP NVARCHAR(50) NOT NULL,
	LUONG int NOT NULL,
	PHUCAP int,
)

CREATE TABLE NHANVIEN
(
	MANV INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENNV NVARCHAR(50) NOT NULL,
	MABP INT NOT NULL,
	SDT CHAR(11) NOT NULL,
	DIACHI NVARCHAR(50),
	GIOITINH NVARCHAR(50) NOT NULL,
	TONGLUONG int,
	CONSTRAINT FK_NHANVIEN_BOPHANLAMVIEC FOREIGN KEY (MABP) REFERENCES BOPHANLAMVIEC(MABP)
)

CREATE TABLE HOADON
(
	MAHD INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MACTHD INT NOT NULL,
	MAKH INT  ,
	TENKH NVARCHAR(50) ,
	TONGTIEN INT,
	NGAYBAN DATE,
	CONSTRAINT FK_HOADON FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	constraint FK_HD1 foreign key(MACTHD) references CHITIETHOADON(MACTHD)
)

CREATE TABLE CHITIETHOADON
(
	MACTHD INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TenSanPham nvarchar(50) not null,
	SOLUONG INT NOT NULL,
	GIAMGIA int,
	DONGIA int ,
	CONSTRAINT FK_CTHD FOREIGN KEY(TenSanPham) REFERENCES SANPHAM(TENSP),
)

create table signin
(
	usename nvarchar(50) primary key,
	pass nvarchar(50),
)
--TAO TRIGGER TU CAP NHAT TEN KHACH HANG
CREATE TRIGGER CAPNHATEN ON HOADON
FOR INSERT 
AS
UPDATE HOADON
SET HOADON.MAKH=KHACHHANG.MAKH
FROM HOADON 
INNER JOIN KHACHHANG
ON(HOADON.TENKH=KHACHHANG.HOTEN)

-----------------------------------------
--TAO TRIGGER AUTO CAP NHAT DONVITINH TRONG HOA DON
CREATE TRIGGER DVT ON CHITIETHOADON
FOR INSERT 
AS
UPDATE CHITIETHOADON
SET CHITIETHOADON.DONGIA=SANPHAM.DONGIABAN
FROM CHITIETHOADON
INNER JOIN SANPHAM
ON(CHITIETHOADON.TenSanPham=SANPHAM.TENSP)

--------------------------------------------------
--trigger tinh tong tien
CREATE trigger capnhaptongtien on hoadon
for insert
as
UPDATE HOADON
SET TONGTIEN=((SOLUONG*DONGIA) + GIAMGIA) FROM CHITIETHOADON
WHERE HOADON.MACTHD=CHITIETHOADON.MACTHD
---------------------------------------------------
--triger cập nhật tổng lương
create trigger TongLuong on NHANVIEN
for INSERT
as
UPDATE NHANVIEN
set TONGLUONG = Luong+PhuCap from BOPHANLAMVIEC
where BOPHANLAMVIEC.MABP=NHANVIEN.MABP
--
drop table HOADON
drop table CHITIETHOADON
INSERT INTO signin values('cuutri',123)

INSERT INTO KHACHHANG VALUES(N'NGUYỄN CỬU TRÍ','0935730047',N'NHA TRANG','NAM')
INSERT INTO KHACHHANG VALUES(N'HÀ ANH TUẤN','0935735747',N'HÀ NỘI','NAM')
INSERT INTO KHACHHANG VALUES(N'VŨ NHẬT LINH','0945474047',N'NHA TRANG',N'NỮ')
INSERT INTO KHACHHANG VALUES(N'NGUYỄN NGỌC ÁNH','0935747447',N'TP.HCM',N'NỮ')
INSERT INTO KHACHHANG VALUES(N'LƯƠNG CỬU LONG','0935730047',N'BIÊN HÒA','NAM')

INSERT INTO SANPHAM VALUES(N'CAFE',N'CAFE',5000,15000)
INSERT INTO SANPHAM VALUES(N'NƯỚC CHANH',N'CHANH',5000,25000)
INSERT INTO SANPHAM VALUES(N'NƯỚC ÉP DƯA HẤU',N'DƯA HẤU',10000,35000)
INSERT INTO SANPHAM VALUES(N'NƯỚC ÉP CHANH DÂY',N'CHANH DÂY',9000,30000)
INSERT INTO SANPHAM VALUES(N'NƯỚC CAM',N'CAM',15000,40000)

SET DATEFORMAT dmy 
INSERT INTO HOADON(MACTHD,TENKH,NGAYBAN) 
VALUES(2,N'NGUYỄN CỬU TRÍ','12/02/2020'),
(3,N'VŨ NHẬT LINH','16/06/2017'),
(5,N'NGUYỄN NGỌC ÁNH','14/03/2013'),
(1,N'HÀ ANH TUẤN','13/06/2016'),
(4,N'LƯƠNG CỬU LONG','20/05/2015')

INSERT INTO CHITIETHOADON(TENSANPHAM,SOLUONG,GIAMGIA)
 VALUES(N'cafe',5,20000),
(N'Nước cam',3,25000),
(N'Nước chanh',5,27000),
(N'cafe',7,25000),
(N'Nước ép chanh dây',1,22000)



INSERT INTO BOPHANLAMVIEC VALUES(N'Thu Ngân', 6000000, 500000)
INSERT INTO BOPHANLAMVIEC VALUES(N'Phục vụ', 4000000, 400000)
INSERT INTO BOPHANLAMVIEC VALUES(N'Tạp vụ', 3500000, 600000)
INSERT INTO BOPHANLAMVIEC VALUES(N'Bảo vệ', 6000000, 800000)
INSERT INTO BOPHANLAMVIEC VALUES(N'pha chế', 5000000, 600000)
INSERT INTO BOPHANLAMVIEC VALUES(N'quản lý', 10000000, 600000)

INSERT INTO NHANVIEN VALUES (N'Trần Văn A',1 , '01256288998', N'Tây Ninh', N'Nam',null)
INSERT INTO NHANVIEN VALUES (N'Nguyễn Văn B',2 , '01256288998', N'Tây Ninh', N'Nam',null)
INSERT INTO NHANVIEN VALUES (N'Nguyễn Thị C',3 , '01256288998', N'Tây Ninh', N'Nữ',null)
INSERT INTO NHANVIEN VALUES (N'Lê Thị D',4 , '01256288998', N'Tây Ninh', N'Nữ',null)
INSERT INTO NHANVIEN VALUES (N'Nguyễn Cửu Trí',6 , '01256288998', N'Tây Ninh', N'Nam',null)

