/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlcafe;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Nhan_Vien;
import pojo.boPhanLamViec;
import qlcafe.Menu;

/**
 *
 * @author PC
 */
public class NhanVien extends javax.swing.JFrame {   
    Connection conn = null;
    Statement statement = null;
    //PreparedStatement reStatement=null;
    ResultSet result = null;
    DefaultTableModel dtmNhanVien;
    Nhan_Vien nvSelected;
    boPhanLamViec bpSelected;

    /**
     * Creates new form NhanVien
     */
    public NhanVien() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Quản lý nhân viên - JDBC Demo");
        dtmNhanVien = (DefaultTableModel) this.tblDSNhanVien.getModel();
        ketNoiCSDL();
        hienThiBoPhanLV();
        hienThiDSNV();
    }

    public boolean kiemTraMaSoTonTai(String maso) {
        try {
            String sqlSelect = "SELECT *FROM NHANVIEN WHERE MANV = '" + maso + "'";
            result = statement.executeQuery(sqlSelect);
            if (result.next()) {
                return true;
            } else {
                return false;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        pnBoPhanLV = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbbBoPhanLV = new javax.swing.JComboBox<>();
        btnTim = new javax.swing.JButton();
        txtTimTenNV = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        pnCT_DSNV = new javax.swing.JPanel();
        pnCTNV = new javax.swing.JPanel();
        lblTenNV = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblGoiTinh = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtGioiTinh = new javax.swing.JTextField();
        lblMaBP = new javax.swing.JLabel();
        lblLuong2 = new javax.swing.JLabel();
        txtMaBP = new javax.swing.JTextField();
        txtLuong = new javax.swing.JTextField();
        pnDSNV = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDSNhanVien = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        pnNutLenh = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnBoPhanLV.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setText("Chọn bộ phận làm việc:");

        cbbBoPhanLV.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbbBoPhanLVPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbbBoPhanLV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbBoPhanLVMouseClicked(evt);
            }
        });
        cbbBoPhanLV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbBoPhanLVActionPerformed(evt);
            }
        });

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (1).png"))); // NOI18N
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/smart-home.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBoPhanLVLayout = new javax.swing.GroupLayout(pnBoPhanLV);
        pnBoPhanLV.setLayout(pnBoPhanLVLayout);
        pnBoPhanLVLayout.setHorizontalGroup(
            pnBoPhanLVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBoPhanLVLayout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbbBoPhanLV, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtTimTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnBoPhanLVLayout.setVerticalGroup(
            pnBoPhanLVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBoPhanLVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBoPhanLVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbBoPhanLV)
                    .addComponent(txtTimTenNV)
                    .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addGroup(pnBoPhanLVLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnCTNV.setBackground(new java.awt.Color(153, 255, 153));
        pnCTNV.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Chi tiết nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        lblTenNV.setText("Tên NV:");

        lblSDT.setText("SĐT:");

        lblMaNV.setText("Mã NV:");

        lblDiaChi.setText("Địa chỉ:");

        lblGoiTinh.setText("Gới tính:");

        lblMaBP.setText("Mã BP:");

        lblLuong2.setText("Lương:");

        txtLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCTNVLayout = new javax.swing.GroupLayout(pnCTNV);
        pnCTNV.setLayout(pnCTNVLayout);
        pnCTNVLayout.setHorizontalGroup(
            pnCTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCTNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCTNVLayout.createSequentialGroup()
                        .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCTNVLayout.createSequentialGroup()
                        .addComponent(lblGoiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCTNVLayout.createSequentialGroup()
                        .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCTNVLayout.createSequentialGroup()
                        .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCTNVLayout.createSequentialGroup()
                        .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCTNVLayout.createSequentialGroup()
                        .addComponent(lblMaBP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaBP, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCTNVLayout.createSequentialGroup()
                        .addComponent(lblLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCTNVLayout.setVerticalGroup(
            pnCTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCTNVLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnCTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaBP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaBP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGoiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnDSNV.setBackground(new java.awt.Color(153, 255, 153));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblDSNhanVien.setBackground(new java.awt.Color(204, 204, 255));
        tblDSNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên NV", "Mã BP", "SĐT", "Địa chỉ", "Giới tính", "Tổng lương"
            }
        ));
        tblDSNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDSNhanVien);
        if (tblDSNhanVien.getColumnModel().getColumnCount() > 0) {
            tblDSNhanVien.getColumnModel().getColumn(1).setMinWidth(100);
            tblDSNhanVien.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jButton3.setText("Cập nhật lương");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDSNVLayout = new javax.swing.GroupLayout(pnDSNV);
        pnDSNV.setLayout(pnDSNVLayout);
        pnDSNVLayout.setHorizontalGroup(
            pnDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
            .addGroup(pnDSNVLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3))
        );
        pnDSNVLayout.setVerticalGroup(
            pnDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDSNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnCT_DSNVLayout = new javax.swing.GroupLayout(pnCT_DSNV);
        pnCT_DSNV.setLayout(pnCT_DSNVLayout);
        pnCT_DSNVLayout.setHorizontalGroup(
            pnCT_DSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCT_DSNVLayout.createSequentialGroup()
                .addComponent(pnCTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDSNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCT_DSNVLayout.setVerticalGroup(
            pnCT_DSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDSNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnCT_DSNVLayout.createSequentialGroup()
                .addComponent(pnCTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        btnThem.setText("Thêm NV");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/floppy-disk (1).png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x-button.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton1.setText("Trở về");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnNutLenhLayout = new javax.swing.GroupLayout(pnNutLenh);
        pnNutLenh.setLayout(pnNutLenhLayout);
        pnNutLenhLayout.setHorizontalGroup(
            pnNutLenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNutLenhLayout.createSequentialGroup()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnNutLenhLayout.setVerticalGroup(
            pnNutLenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNutLenhLayout.createSequentialGroup()
                .addGroup(pnNutLenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnNutLenhLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnNutLenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBoPhanLV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnCT_DSNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnNutLenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnBoPhanLV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnCT_DSNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnNutLenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbBoPhanLVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbBoPhanLVActionPerformed
        // TODO add your handling code here:
        try {
            String tenbp = cbbBoPhanLV.getSelectedItem().toString();
            String sql = "SELECT MANV, TENNV, NHANVIEN.MABP, SDT, DIACHI, GIOITINH, TONGLUONG FROM NHANVIEN, BOPHANLAMVIEC where NHANVIEN.MABP=BOPHANLAMVIEC.MABP AND TENBP=N'" + tenbp+"'";
            //statement = conn.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            dtmNhanVien.setRowCount(0);           
            while (rs.next()) {
                String ma = rs.getString(1);
                String tennv = rs.getString(2);
                String mabp = rs.getString(3);
                String sdt = rs.getString(4);
                String diachi = rs.getString(5);
                String gioitinh = rs.getString(6);
                String tongluong = rs.getString(7);
                Vector<Object> vec = new Vector<Object>();
                vec.add(ma);
                vec.add(tennv);
                vec.add(mabp);
                vec.add(sdt);
                vec.add(diachi);
                vec.add(gioitinh);
                vec.add(tongluong);
                dtmNhanVien.addRow(vec);
            }           
        }catch(Exception ex){
            ex.printStackTrace();
        }            
    }//GEN-LAST:event_cbbBoPhanLVActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        txtMaNV.setText("");
        txtTenNV.setText("");
        txtMaBP.setText("");
        txtSDT.setText("");
        txtDiaChi.setText("");
        txtGioiTinh.setText("");
        txtLuong.setText("");
         txtTenNV.requestFocus();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (tblDSNhanVien.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "vui lòng chọn trước khi xóa");
            return;
        }
        int ques = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa không",
                "xóa danh sách?", JOptionPane.YES_NO_OPTION);
        if (ques == JOptionPane.NO_OPTION) {
            return;
        } else {
            try {
                String sqlXoa = "DELETE FROM NHANVIEN WHERE MANV = '" + txtMaNV.getText() + "'";
                int x = statement.executeUpdate(sqlXoa);
                if (x > 0) {
                    hienThiDSNV();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblDSNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSNhanVienMouseClicked
        // TODO add your handling code here:
        int rowSelected = this.tblDSNhanVien.getSelectedRow();
        txtMaNV.setText((String)tblDSNhanVien.getValueAt(rowSelected, 0));
        txtTenNV.setText((String) tblDSNhanVien.getValueAt(rowSelected, 1));
        txtMaBP.setText((String) tblDSNhanVien.getValueAt(rowSelected, 2));
        txtSDT.setText((String) tblDSNhanVien.getValueAt(rowSelected, 3));
        txtDiaChi.setText((String) tblDSNhanVien.getValueAt(rowSelected, 4));
        txtGioiTinh.setText((String) tblDSNhanVien.getValueAt(rowSelected, 5));
        txtLuong.setText(tblDSNhanVien.getValueAt(rowSelected, 6) + "");
    }//GEN-LAST:event_tblDSNhanVienMouseClicked

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if (kiemTraMaSoTonTai(txtMaNV.getText()) == true) {
            //khách hàng này đã tồn tại
            int tl = JOptionPane.showConfirmDialog(null,
                    "Mã đã tồn tại, bạn có muốn cập nhật?",
                    "Trùng Mã số", JOptionPane.YES_NO_OPTION);
            if (tl == JOptionPane.NO_OPTION) {
                return;
            } else {
                //trường họp usre muốn cập nhật (update) họ tên, năm sinh
                try {
                    //UPDATE NHANVIEN SET TENNV = N'Nguyễn Văn A',  MABP= 1, SDT='12537236736', DIACHI=N'Tây Ninh', GIOITINH = N'Nam', TONGLUONG = 100000 WHERE MANV =20 WHERE MaKH ='KH01'
                    String sqlUpdate = "UPDATE NHANVIEN SET TENNV = N'"
                            + txtTenNV.getText() + "', MABP = " + txtMaBP.getText() + ", SDT='" + txtSDT.getText() + "', DIACHI=N'" + txtDiaChi.getText() + "', GIOITINH= N'" 
                            + txtGioiTinh.getText() +"', TONGLUONG = "+txtLuong.getText()+" WHERE MANV = "+ txtMaNV.getText();
                    int x = statement.executeUpdate(sqlUpdate);
                    if (x > 0) {
                        hienThiDSNV();
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        } else //trường hợp mã chưa tồn tại -->thêm khách hàng mới
        {
            try {
                //INSERT INTO NhanVien VALUES(N'Trương Tam Phong', 1, '1523765878',N'Tây Ninh',N'Nam',10000000)
                String sqlInsert = "INSERT INTO NHANVIEN VALUES(N'"
                        + txtTenNV.getText() + "', " + txtMaBP.getText() + ", '" + txtSDT.getText() + "', N'" + txtDiaChi.getText() + "',N'" + txtGioiTinh.getText() + "',"+null+")";
                int x = statement.executeUpdate(sqlInsert);
                if (x > 0) {
                    hienThiDSNV();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(null, "Bạn mún thoát Phải không?",
                "Thoát", JOptionPane.YES_NO_CANCEL_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else if (n == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Không thoát thì thôi");
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void cbbBoPhanLVPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbbBoPhanLVPopupMenuWillBecomeInvisible
         //TODO add your handling code here:
    }//GEN-LAST:event_cbbBoPhanLVPopupMenuWillBecomeInvisible

    private void cbbBoPhanLVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbBoPhanLVMouseClicked
         //TODO add your handling code here:
    }//GEN-LAST:event_cbbBoPhanLVMouseClicked

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        try{
        String sql = "SELECT * FROM NHANVIEN WHERE TENNV like N'"+txtTimTenNV.getText()+"%'";
        ResultSet rs = statement.executeQuery(sql);
            dtmNhanVien.setRowCount(0);
            
            while (rs.next()) {
                String ma = rs.getString(1);
                String tennv = rs.getString(2);
                String mabp = rs.getString(3);
                String sdt = rs.getString(4);
                String diachi = rs.getString(5);
                String gioitinh = rs.getString(6);
                String tongluong = rs.getString(7);
                Vector<Object> vec = new Vector<Object>();
                vec.add(ma);
                vec.add(tennv);
                vec.add(mabp);
                vec.add(sdt);
                vec.add(diachi);
                vec.add(gioitinh);
                vec.add(tongluong);
                dtmNhanVien.addRow(vec);
            }
        }catch(Exception ex){
            ex.printStackTrace();           
        }                   
    }//GEN-LAST:event_btnTimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        NhanVien nv = new NhanVien();
        nv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu mn= new Menu();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuongActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        BoPhanLamViec bp= new BoPhanLamViec();
        bp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void hienThiBoPhanLV() {
        String sql = "SELECT *FROM BOPHANLAMVIEC";
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                this.cbbBoPhanLV.addItem(rs.getString("TENBP"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void hienThiDSNV() {
        try {
            String sql = "SELECT * FROM NHANVIEN";
            
            result = statement.executeQuery(sql);
            dtmNhanVien.setRowCount(0);
            while (result.next()) {
                String ma = result.getString("MANV");
                String tennv = result.getString("TENNV");
                String mabp = result.getString("MABP");
                String sdt = result.getString("SDT");
                String diachi = result.getString("DIACHI");
                String gioitinh = result.getString("GIOITINH");
                String tongluong = result.getString("TONGLUONG");
                Vector<Object> vec = new Vector<Object>();
                vec.add(ma);
                vec.add(tennv);
                vec.add(mabp);
                vec.add(sdt);
                vec.add(diachi);
                vec.add(gioitinh);
                vec.add(tongluong);
                dtmNhanVien.addRow(vec);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVien().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbBoPhanLV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblGoiTinh;
    private javax.swing.JLabel lblLuong2;
    private javax.swing.JLabel lblMaBP;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JPanel pnBoPhanLV;
    private javax.swing.JPanel pnCTNV;
    private javax.swing.JPanel pnCT_DSNV;
    private javax.swing.JPanel pnDSNV;
    private javax.swing.JPanel pnNutLenh;
    private javax.swing.JTable tblDSNhanVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaBP;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTimTenNV;
    // End of variables declaration//GEN-END:variables

    private void ketNoiCSDL() {
        String strServer = "DESKTOP-1ON6LLQ\\SQLEXPRESS";
        String strDatabase = "DB_QLCAFE";
        String strUsername = "sa";
        String strPassword = "123";
        try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String connectionURL = "jdbc:sqlserver://" + strServer
                                + ":1433;databaseName=" + strDatabase 
                                + ";user=" + strUsername + ";password=" + strPassword;
                conn = DriverManager.getConnection(connectionURL);                
                statement = conn.createStatement(
                                ResultSet.TYPE_SCROLL_INSENSITIVE,
                                ResultSet.CONCUR_READ_ONLY);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
